// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJOtfIejPq7EJaRP37qmGXDQYVWtwI5qk',
    appId: '1:8084182968:web:d115a007cbe6aed811214d',
    messagingSenderId: '8084182968',
    projectId: 'estate-ease-7ab0b',
    authDomain: 'estate-ease-7ab0b.firebaseapp.com',
    storageBucket: 'estate-ease-7ab0b.appspot.com',
    measurementId: 'G-FXZ7X5BYV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNzav5gxDSe1zyamH_hJcVsHCaUuK-wuU',
    appId: '1:8084182968:android:8ff3c2dae1a910b711214d',
    messagingSenderId: '8084182968',
    projectId: 'estate-ease-7ab0b',
    storageBucket: 'estate-ease-7ab0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAq_EbtRQ9i-QtjgZQFXGUscuJ2yNBl-Y',
    appId: '1:8084182968:ios:cb83a1135f2c6c9311214d',
    messagingSenderId: '8084182968',
    projectId: 'estate-ease-7ab0b',
    storageBucket: 'estate-ease-7ab0b.appspot.com',
    iosBundleId: 'com.example.estateEase',
  );
}
